package jStrg.GWT.client.service;

import com.google.gwt.user.client.rpc.AsyncCallback;

/**
 * Created by Jura on 15.05.2016.
 * GWT autogenerated Interface
 */
public interface ServiceAsync {
    void login(String name, String password, AsyncCallback async);

    void getFolderById(int folder_id, AsyncCallback<String> async);

    void getFileById(int file_id, AsyncCallback<String> async);

    void renameFolder(int folder_id, String newTitle, AsyncCallback<String> async);

    void createFolder(int app_id, int parent_id, String title, AsyncCallback<String> async);

    void deleteFolder(int folder_id, AsyncCallback<String> async);

    void renameFile(int file_id, String newTitle, AsyncCallback<String> async);

    void deleteFile(int file_id, AsyncCallback<String> async);

    void loginFromSession(AsyncCallback<String> async);

    void logout(AsyncCallback<Void> async);

    void getFileVersionList(int file_id, AsyncCallback<String> async);

    void rollbackToVersion(int version_id, AsyncCallback<String> async);
}
